### ISSUE TITLE
Store Notes in Database

### ISSUE THREAD

**Issue by DrewCaylor** [cs130-w21/2#53] opened 2021-02-16 23:59 UTC
## User Story
As a User, I would like my notes to be stored in a database so that they can be accessed later.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [ ] When note is created, note will be stored in the database

**Comment by jasonpanelli** [comment] 2021-02-17 01:41
Is this duplicate of #55 which is part of #6 story

**Comment by jasonpanelli** [comment] 2021-02-19 05:33
Closed #55, use this issue instead

**Comment by jasonpanelli** [comment] 2021-02-24 08:18
Closely associated with #7 and #8

**Closed** 2021-02-27 00:03 UTC
Labels: story
